apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: demobaz-pipeline
      app: demobaz-pipeline
    name: demobaz-pipeline
  spec:
    successfulBuildHistoryLimit: 2
    failedBuildHistoryLimit: 2
    source:
      git:
        uri: http://gogs-cicd.apps.openshift-lab.com/moloa/demobaz.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: FiArdDBH
      type: Generic