apiVersion: v1
kind: Template
metadata:
  annotations:
    iconClass: icon-java
  labels:
    app: demobaz-cicd
  name: demo-app-template
objects:
- apiVersion: v1
  kind: Deployment
  metadata:
    labels:
      app: demobaz-cicd
      run: demobaz-cicd-deploy
    name: demobaz-cicd-deploy
  spec:
    replicas: 1
    selector:
      app: demobaz-cicd
      deploymentconfig: demobaz-cicd
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: demobaz-cicd
          deploymentconfig: demobaz-cicd
          docker-registry: default
      spec:
        containers:
        - image: ""
          imagePullPolicy: Always
          name: app
          ports:
          - containerPort: 9000
            protocol: TCP
          resources: 
            requests:
              cpu: 100m
              memory: 128MB
            limits:
              cpu: 500m
              memory: 512MB
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: demobaz-cicd
      deploymentconfig: demobaz-cicd
    name: demobaz-cicd-service
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 9000
    selector:
      deploymentconfig: demobaz-cicd
      docker-registry: default
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: demobaz-cicd
      deploymentconfig: demobaz-cicd
    name: demobaz-cicd
  spec:
    to:
      kind: Service
      name: demobaz-cicd-service
  value: "true"